# theme: jekyll-theme-midnight
# remote_theme: just-the-docs/just-the-docs

title: Solidity Guide
description: Cheatsheet and best practices for Solidity
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Required for remote_theme
plugins:
  - jekyll-remote-theme

# Optional
search_enabled: true
